# coding: utf-8

"""
    TechPort

    TechPort RESTful API

    The version of the OpenAPI document: 3.13.2
    Contact: hq-techport@mail.nasa.gov
    Created by: https://techport.nasa.gov
"""

from nasa_tech_port_python_sdk.paths.api_organizations_organization_id.get import GetInformation
from nasa_tech_port_python_sdk.paths.api_organizations.get import GetListByName
from nasa_tech_port_python_sdk.paths.api_organizations_types.get import ListTypes
from nasa_tech_port_python_sdk.apis.tags.organization_api_raw import OrganizationApiRaw


class OrganizationApi(
    GetInformation,
    GetListByName,
    ListTypes,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OrganizationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OrganizationApiRaw(api_client)
