# coding: utf-8

"""
    TechPort

    TechPort RESTful API

    The version of the OpenAPI document: 3.13.2
    Contact: hq-techport@mail.nasa.gov
    Created by: https://techport.nasa.gov
"""

from nasa_tech_port_python_sdk.paths.api_organizations_organization_id.get import GetInformationRaw
from nasa_tech_port_python_sdk.paths.api_organizations.get import GetListByNameRaw
from nasa_tech_port_python_sdk.paths.api_organizations_types.get import ListTypesRaw


class OrganizationApiRaw(
    GetInformationRaw,
    GetListByNameRaw,
    ListTypesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
