# coding: utf-8

"""
    TechPort

    TechPort RESTful API

    The version of the OpenAPI document: 3.13.2
    Contact: hq-techport@mail.nasa.gov
    Created by: https://techport.nasa.gov
"""

from nasa_tech_port_python_sdk.paths.api_projects_search.get import FindMatchingProjectsRaw
from nasa_tech_port_python_sdk.paths.api_projects_project_id.get import GetInfoRaw
from nasa_tech_port_python_sdk.paths.api_projects.get import ListAvailableIdsRaw


class ProjectApiRaw(
    FindMatchingProjectsRaw,
    GetInfoRaw,
    ListAvailableIdsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
