# coding: utf-8

"""
    TechPort

    TechPort RESTful API

    The version of the OpenAPI document: 3.13.2
    Contact: hq-techport@mail.nasa.gov
    Created by: https://techport.nasa.gov
"""

from nasa_tech_port_python_sdk.paths.api_projects_search.get import FindMatchingProjects
from nasa_tech_port_python_sdk.paths.api_projects_project_id.get import GetInfo
from nasa_tech_port_python_sdk.paths.api_projects.get import ListAvailableIds
from nasa_tech_port_python_sdk.apis.tags.project_api_raw import ProjectApiRaw


class ProjectApi(
    FindMatchingProjects,
    GetInfo,
    ListAvailableIds,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ProjectApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ProjectApiRaw(api_client)
