# coding: utf-8

"""
    TechPort

    TechPort RESTful API

    The version of the OpenAPI document: 3.13.2
    Contact: hq-techport@mail.nasa.gov
    Created by: https://techport.nasa.gov
"""

from nasa_tech_port_python_sdk.paths.api.get import GetSpecification
from nasa_tech_port_python_sdk.apis.tags.resource_api_raw import ResourceApiRaw


class ResourceApi(
    GetSpecification,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ResourceApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ResourceApiRaw(api_client)
